(function($) {
    $(document).ready(function() {
	
	$('#graph').scianimator({
	    'images': ['animation/graph1.png', 'animation/graph2.png', 'animation/graph3.png', 'animation/graph4.png', 'animation/graph5.png', 'animation/graph6.png', 'animation/graph7.png', 'animation/graph8.png', 'animation/graph9.png', 'animation/graph10.png', 'animation/graph11.png', 'animation/graph12.png', 'animation/graph13.png', 'animation/graph14.png', 'animation/graph15.png', 'animation/graph16.png', 'animation/graph17.png', 'animation/graph18.png', 'animation/graph19.png', 'animation/graph20.png', 'animation/graph21.png', 'animation/graph22.png', 'animation/graph23.png', 'animation/graph24.png', 'animation/graph25.png', 'animation/graph26.png', 'animation/graph27.png', 'animation/graph28.png', 'animation/graph29.png', 'animation/graph30.png', 'animation/graph31.png', 'animation/graph32.png', 'animation/graph33.png', 'animation/graph34.png', 'animation/graph35.png', 'animation/graph36.png', 'animation/graph37.png', 'animation/graph38.png', 'animation/graph39.png', 'animation/graph40.png', 'animation/graph41.png', 'animation/graph42.png', 'animation/graph43.png', 'animation/graph44.png', 'animation/graph45.png', 'animation/graph46.png', 'animation/graph47.png', 'animation/graph48.png', 'animation/graph49.png', 'animation/graph50.png', 'animation/graph51.png', 'animation/graph52.png', 'animation/graph53.png', 'animation/graph54.png', 'animation/graph55.png', 'animation/graph56.png', 'animation/graph57.png', 'animation/graph58.png', 'animation/graph59.png', 'animation/graph60.png', 'animation/graph61.png', 'animation/graph62.png', 'animation/graph63.png', 'animation/graph64.png', 'animation/graph65.png', 'animation/graph66.png', 'animation/graph67.png', 'animation/graph68.png', 'animation/graph69.png', 'animation/graph70.png', 'animation/graph71.png', 'animation/graph72.png', 'animation/graph73.png', 'animation/graph74.png', 'animation/graph75.png', 'animation/graph76.png', 'animation/graph77.png', 'animation/graph78.png', 'animation/graph79.png', 'animation/graph80.png', 'animation/graph81.png', 'animation/graph82.png', 'animation/graph83.png', 'animation/graph84.png', 'animation/graph85.png', 'animation/graph86.png', 'animation/graph87.png', 'animation/graph88.png', 'animation/graph89.png', 'animation/graph90.png', 'animation/graph91.png', 'animation/graph92.png', 'animation/graph93.png', 'animation/graph94.png', 'animation/graph95.png', 'animation/graph96.png', 'animation/graph97.png', 'animation/graph98.png', 'animation/graph99.png', 'animation/graph100.png', 'animation/graph101.png', 'animation/graph102.png', 'animation/graph103.png'],
	    'width': 480,
	    'delay': 2000,
	    'loopMode': 'loop',
 'width': 600
	});
    });
})(jQuery);
